include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    unused_import: error
    unused_local_variable: error
    dead_code: error
    unnecessary_cast: error
    always_declare_return_types: error

linter:
  rules:
    directives_ordering: true
    prefer_single_quotes: true
    prefer_final_locals: true
    use_super_parameters: true
    unnecessary_lambdas: true
    always_use_package_imports: true
    avoid_relative_lib_imports: true
